name: cosmetics_shop
description: A new Cosmetics App.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.10.0
  fluttertoast: ^7.1.6
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_ic.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/launcher_ic.png
    - assets/images/products/
    - assets/images/misc/
    - assets/images/categories/

  fonts:
    - family: Calibri
      fonts:
        - asset: fonts/Calibri Regular.ttf
    - family: Arial
      fonts:
        - asset: fonts/arial.ttf
    - family: Century-Gothic
      fonts:
        - asset: fonts/Century Gothic 400.ttf
    - family: Roboto-ThinItalic
      fonts:
        - asset: fonts/Roboto-ThinItalic.ttf
    - family: Roboto-BlackItalic
      fonts:
        - asset: fonts/Roboto-BlackItalic.ttf
    - family: Roboto-Black
      fonts:
        - asset: fonts/Roboto-Black.ttf         
    - family: Roboto-Bold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: Roboto-BoldItalic
      fonts:
        - asset: fonts/Roboto-BoldItalic.ttf 
    - family: Roboto-Italic
      fonts:        
        - asset: fonts/Roboto-Italic.ttf
    - family: Roboto-Light
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: Roboto-LightItalic
      fonts:
        - asset: fonts/Roboto-LightItalic.ttf
    - family: Roboto-Medium
      fonts:
        - asset: fonts/Roboto-Medium.ttf      
    - family: Roboto-Regulat
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Roboto-Thin
      fonts:
        - asset: fonts/Roboto-Thin.ttf         