name: cosmetics_shop
description: A new Cosmetics App.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.1
  path: ^1.8.0

  fluttertoast: ^8.0.8 #toast message
  intl: ^0.17.0 #date-time
  flutter_launcher_icons: ^0.9.2 #app icon
  form_field_validator: ^1.1.0 #regexp
  firebase_core: ^1.12.0 #firebase
  cloud_firestore: ^3.1.7 #database
  provider: ^6.0.2 #state management

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_ic.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/launcher_ic.png
    - assets/images/products/
    - assets/images/misc/
    - assets/images/categories/

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/Calibri Regular.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf
    - family: Century-Gothic
      fonts:
        - asset: assets/fonts/Century Gothic 400.ttf
    - family: Roboto-ThinItalic
      fonts:
        - asset: assets/fonts/Roboto-ThinItalic.ttf
    - family: Roboto-BlackItalic
      fonts:
        - asset: assets/fonts/Roboto-BlackItalic.ttf
    - family: Roboto-Black
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf         
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-BoldItalic
      fonts:
        - asset: assets/fonts/Roboto-BoldItalic.ttf 
    - family: Roboto-Italic
      fonts:        
        - asset: assets/fonts/Roboto-Italic.ttf
    - family: Roboto-Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Roboto-LightItalic
      fonts:
        - asset: assets/fonts/Roboto-LightItalic.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf      
    - family: Roboto-Thin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf         